version: '2'

services:
  app:
    image: 'application-analythics:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/volgadb
      - DATASOURCE_USERNAME=volgadb
      - DATASOURCE_PASSWORD=dm9sZ2FkYnBhc3N3b3Jk

  db:
    image: 'postgres:alpine'
    container_name: db
    environment:
      - POSTGRES_USER=volgadb
      - POSTGRES_PASSWORD=dm9sZ2FkYnBhc3N3b3Jk